#
# Nastavení termínů uploadu (DEADLINE) a termínu odeslání (DEADLINES)
# ve formátu pro TeX i "strojové" zpracování".
# Očekávaný formát "dd.~MM.~yyyy hh.mm", čas je nepovinný, implicitně 23.59.
#

DEADLINE[1]=15.~10.~2013 20.00
DEADLINES[1]=14.~10.~2013

DEADLINE[2]=3.~12.~2013 20.00
DEADLINES[2]=2.~12.~2013

DEADLINE[3]=21.~1.~2014 20.00
DEADLINES[3]=20.~1.~2014

DEADLINE[4]=4.~3.~2014 20.00
DEADLINES[4]=3.~3.~2014

DEADLINE[5]=15.~4.~2014 20.00
DEADLINES[5]=14.~4.~2014

DEADLINE[6]=20.~5.~2014 20.00
DEADLINES[6]=19.~5.~2014
