# Makefile part for problems dependent images
GRAPHICS=graphics/

.PHONY: \
problem1-1 problem1-2 problem1-3 problem1-4 problem1-5 problem1-6 problem1-7 problem1-8 \
problem2-1 problem2-2 problem2-3 problem2-4 problem2-5 problem2-6 problem2-7 problem2-8 \
problem3-1 problem3-2 problem3-3 problem3-4 problem3-5 problem3-6 problem3-7 problem3-8 \
problem4-1 problem4-2 problem4-3 problem4-4 problem4-5 problem4-6 problem4-7 problem4-8 \
problem5-1 problem5-2 problem5-3 problem5-4 problem5-5 problem5-6 problem5-7 problem5-8 \
problem6-1 problem6-2 problem6-3 problem6-4 problem6-5 problem6-6 problem6-7 problem6-8


problem1-1:
problem1-2:
problem1-3:
problem1-4:
problem1-5:
problem1-6:
problem1-7:
problem1-8:                                                                                           
                                                                                                      
problem2-1:                                                                                           
problem2-2:                                                                                           
problem2-3:                                                                                           
problem2-4:                                                                                           
problem2-5:                                                                                           
problem2-6:                                                                                           
problem2-7:                                                                                           
problem2-8:                                                                                           
                                                                                                      
problem3-1:                                                                                           
problem3-2:
problem3-3:
problem3-4:
problem3-5:
problem3-6:
problem3-7:
problem3-8:

problem4-1:
problem4-2:
problem4-3:
problem4-4:
problem4-5:
problem4-6:
problem4-7:
problem4-8:

problem5-1:
problem5-2:
problem5-3:
problem5-4:
problem5-5:
problem5-6:
problem5-7:
problem5-8:

problem6-1:
problem6-2:
problem6-3:
problem6-4:
problem6-5:
problem6-6:
problem6-7:
problem6-8:


